[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'Shougo/context_filetype.vim'
hook_add = '''
source ~/.vim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add ='''
source ~/.vim/plugins/LanguageClient-neovim.rc.vim
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'simeji/winresizer'
