[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hood_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/Vim-R-plugin'
on_ft = 'r'

[[plugins]]
repo = 'eigenfoo/stan-vim'
on_ft = 'stan'

[[plugins]]
repo = 'puremourning/vimspector'
on_ft = ['rust', 'c++', 'python']
build = "./install_gadget.py --enable-python --force-enable-rust"
hook_add ='''
source ~/.config/nvim/plugins/vimspector.rc.vim
'''
