[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
on_ft = ['python']

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = ['python']

[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_ft = ['rust', 'c++', 'python']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['rust', 'python']

