[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = '''
source ~/.config/nvim/plugins/ddc.rc.vim
'''

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'LumaKernel/ddc-file'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
hook_add = '''
call popup_preview#enable()
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_add = '''
source ~/.config/nvim/plugins/vim-vsnip.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
colorscheme onedark
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = 'TSUpdate'
hook_add = '''
lua << EOF
-- require('nvim_treesitter_rc')
require('nvim-treesitter.configs').setup {
  ensure_installed = {
	"bash",
	"c",
	"cmake",
	"cpp",
	"css",
	"cuda",
	"diff",
	"dockerfile",
	"gitignore",
	"html",
	"java",
	"javascript",
	"json",
	"lua",
	"make",
	"python",
	"rust",
	"sql",
	"toml",
	"typescript",
	"vim",
	"yaml"
  },
  highlight = {
    enable = true,
    disable = {"rust"},
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
    disable = {},
 },
}
EOF
'''

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
#on_source = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
#on_ft = ['c++', 'rust', 'python', 'sql', 'sh']
depends = ['ray-x/lsp_signature.nvim']
hook_add ='''
lua << EOF
require('lspconfig_rc')
EOF
'''

